### ISSUE TITLE
Sound files should support loading by chunks

### ISSUE THREAD

**Issue by thinlizzy** [rpvelloso/libjukebox#7]
Now they are reading and decoding the entire files, which can drain the application memory if there are too many objects and start causing memory trashing!

Both wav and ogg files have this behavior.

We need a way to specify a maximum chunk size and design some sort of streaming when playing Sound objects.

**Comment by rpvelloso** [comment]
windows/dsound streaming is done.

**Comment by rpvelloso** [comment]
linux/alsa streaming is done
